name: Run Server & Client Tests on PR

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  combined-tests:
    name: Server & Client Combined Tests
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      MONGO_TEST_URI: ${{ secrets.MONGO_TEST_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # Server setup
      - name: Install server dependencies
        run: |
          cd server
          npm ci

      - name: Start server in background
        run: |
          cd server
          npm run dev &

      # Client setup
      - name: Install client dependencies
        run: |
          cd client
          npm ci

      - name: Start client in background
        run: |
          cd client
          npm run dev &

      - name: Wait for client and server to be ready
        run: sleep 15  # You may replace with wait-on for more precision

      - name: Run server tests with coverage
        run: |
          cd server
          npm run test:coverage

      - name: Upload server coverage report
        uses: actions/upload-artifact@v4
        with:
          name: server-coverage-report
          path: server/coverage/

      - name: Run client tests with coverage
        run: |
          cd client
          npm run test:coverage

      - name: Upload client coverage report
        uses: actions/upload-artifact@v4
        with:
          name: client-coverage-report
          path: client/coverage/

      # Run Cypress e2e tests
      - name: Run Cypress tests
        run: |
          cd client
          npm run cypress:open